FROM php:8.2-fpm-alpine

RUN apk --no-cache --update \ 
    add curl \
    icu-dev \
    zlib-dev \
    libpng-dev \
    libjpeg-turbo \
    libwebp \
    freetype \
    php82-apache2 \
    php82-bcmath \
    php82-bz2 \
    php82-calendar \
    php82-common \
    php82-ctype \
    php82-curl \
    php82-dom \
    php82-fileinfo \
    php82-gd \
    php82-iconv \
    php82-json \
    php82-mbstring \
    php82-mysqli \
    php82-mysqlnd \
    php82-openssl \
    php82-pdo_mysql \
    php82-pdo_pgsql \
    php82-pdo_sqlite \
    php82-phar \
    php82-session \
    php82-xml \
    php82-tokenizer \
    php82-zip \
    php82-intl \
    php82-xmlwriter \
    tzdata

RUN docker-php-ext-install mysqli pdo pdo_mysql gd
RUN docker-php-ext-configure intl && docker-php-ext-install intl
RUN docker-php-ext-configure pcntl --enable-pcntl && docker-php-ext-install pcntl;

WORKDIR /var/www
RUN chown 1000:1000 -R /var/www

USER 1000

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

EXPOSE 9000
CMD ["php-fpm"]